source 'https://rubygems.org'

# add runtime dependencies here, they will be included in the index.zip
gem 'httparty'

# This is the aws ruby sdk provides a ruby client for interacting with AWS apis.
# gem 'aws-sdk'

# DO NOT REMOVE; bundler version MUST match the version that the traveling ruby uses, which is currently 1.9.9.
gem 'bundler', '= 1.9.9'

# gems in the development group will not be included in the index.zip
group :development do
  gem 'rumbda'
end
